busybox.bst: Disable the 'tc' applet
Current busybox builds failed at a lot of undefined 'tc; stuff:
/buildstream/endlessos/eos/initramfs/busybox.bst/networking/tc.c: In function cbq_print_opt:
/buildstream/endlessos/eos/initramfs/busybox.bst/networking/tc.c:236:27: error: TCA_CBQ_MAX undeclared (first use in this function); did you mean
<E2><80><98>TCA_CBS_MAX<E2><80><99>?
  236 |         struct rtattr *tb[TCA_CBQ_MAX+1];
      |                           ^~~~~~~~~~~
      |                           TCA_CBS_MAX

It references kernel uapi structs for the CBQ qdisc (e.g. struct
tc_cbq_wrropt) that were removed from linux/pkt_sched.h along with CBQ
support in Linux 6.8 [1], so it no longer builds against current kernel
headers. Not needed in the initramfs. So, simply disable the 'tc'
applet.

[1]: https://lists.busybox.net/pipermail/busybox-cvs/2024-January/041752.html

Fixes: https://github.com/endlessm/eos-build-meta/issues/238